version: '3'

services:
  mariadb:
    image: bitnami/mariadb
    ports:
      - 3306:3306
    environment:
      - MARIADB_ROOT_PASSWORD=docker
      - MARIADB_USER=docker
      - MARIADB_PASSWORD=docker
      - MARIADB_DATABASE=triptact
